<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>
	<body>
		<script>
			const promiseFive = new Promise(function (resolve, reject) {
				let error = false;
				if (!error) {
					resolve({ user: "sunny", pass: 123 });
				} else {
					reject("something went wrong");
				}
			});

			// async await cant handle error directly so..

			async function consumePromiseFive() {
				try {
					const response = await promiseFive;
					console.log(response);
				} catch (error) {
					console.log(error);
				}
			}

			consumePromiseFive();

			//fetching data through urls......

			async function getAllUsers() {
				try {
					const response = fetch(
						"https://jsonplaceholder.typicode.com/users"
					);
					const data = await response.json();
					console.log(data);
				} catch (error) {
					console.log(error);
				}
			}

			// 404 error is not an error, its a response.

			getAllUsers();

			fetch("https://jsonplaceholder.typicode.com/users")
				.then((response) => {
					return response.json();
				})
				.then((data) => {
					console.log(data);
				})
				.catch((error) => {
					console.log(error);
				});
		</script>
	</body>
</html>
